### PR TITLE
added goals.js

### PR DESCRIPTION
**Pull request by a-hend**
Created and updated goals.js with Lesson 3 instructions.

### CODE REVIEW

**Comment by C-STYR** [comment]
Hey Abe, good working attempting Lesson 3. 
I got your PR but `goals.js` doesn't appear to have any content - it's just a blank file.  You may have to change your VS Code save settings (try Files: Auto Save and set to afterDelay); you could also try saving manually, then `git add .` then committing again. Just push another commit to this branch and this PR will update automagically.

**Comment by a-hend** [comment]
Saved goals.js and re-commited; re-pushed to origin.

I tried following your directions, but it said 2 files were changed...and the push was completed with two local objects.  Not sure if I did it right or not.  How does it look on your end?

**Comment by a-hend** [comment]
Oh, maybe its counting the original goals.js and the updated (saved) goals.js since they were two separate commits?

**Comment by C-STYR** [comment]
That worked - the two separate files are `goals.js` and the `hello.js` from your original PR.  You can view them by looking at the `Files changed` tab at the top of this PR page. 
Approved.

**Review by C-STYR — APPROVED** [review]

**Pull request merged**
