### PR TITLE
Attempted to fix the location of isthisworking.txt

### PR DESCRIPTION
**Pull request by a-hend**
Should I have pushed this and created a pull request on the same branch as the previous pull request `abe/isthisworking` since this is an attempted fix for that?

I moved the file `isthisworking.txt` to its correct folder within GitHubTrainer/Users/abehenderson/textfiles/` and deleted the folder `GitHubTrainer` that I had accidentially created outside of the GitHubTrainer clone.  

I'm not even sure how that would have been able to be merged if it was outside the repositor?

I need to watch more vids on this stuff...I still don't think I fully understand whats actually happening :-/

### CODE REVIEW

**Review by C-STYR — APPROVED** [review]
If you merge the first one before this one we might get to explore the fun world of merge conflicts...

**Comment by a-hend** [comment]
Haha ok I'll try it

**Comment by a-hend** [comment]
Aha!  You were right.  We now have conflicting files.

**Comment by C-STYR** [comment]
Cool. You're going to want to use VS Code's to resolve the conflict.
Locally, check out the `main` branch and then `git pull origin main`.  If that doesn't work, stop there and we'll go through it together.  If it does work, after pulling, check out this feature branch and then run `git merge main`.
The conflicts will be flagged in the terminal.  See if you can figure out how to resolve them, and if you can't we'll run through it together. Merge conflicts can be easy or really hard, so don't beat yourself up if you can't work it out. 
Once you've resolved the conflicts, commit and push up to the origin version of this branch and you should see the conflict resolved by GitHub. Proceed as normal with the PR.

**Comment by a-hend** [comment]
Ok perfect thanks for the tips!

**Comment by a-hend** [comment]
Ok I think I got it.  How does it look on your end?

**Pull request merged**
