### PR TITLE
added my goals

### PR DESCRIPTION
**Pull request by KWFelts**
new-branch pull request

### CODE REVIEW

**Comment by C-STYR** [comment]
@KWFelts  got the file (the PR worked). But the file is empty. No contents. Not sure what's going on there, but you need to add and commit after you make any changes...
Try adding something to the file and pushing a new commit to this branch.  Once you've committed locally (`git commit -m "whatever"`) run `git push origin new-branch` again.

**Comment by KWFelts** [comment]
I’ve made a new branch and tried again…fingers crossed.

**Comment by C-STYR** [comment]
Still nothing in this file. Not sure what's going wrong here; can you add some screenshots showing file contents and your terminal commands?

**Comment by KWFelts** [comment]
When I try the process again it says tree empty nothing to commit.  However here is a screenshot of my last session where I believe it says files have been committed.

**Review by C-STYR — APPROVED** [review]

**Comment by C-STYR** [comment]
OK, I've approved, see if you can merge it.

**Comment by KWFelts** [comment]
Trying again

**Comment by KWFelts** [comment]
I think I was getting hung up on the first screen after pull request.  I never changed the branch.  I merged, but after I merged I see that I merged with eefb1ae?

Thanks

**Pull request merged**
